-- MySQL Script generated by MySQL Workbench
-- Tue Oct  4 01:17:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyecto_restaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_restaurante` DEFAULT CHARACTER SET utf8mb3 ;
USE `proyecto_restaurante` ;

-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`gerente` (
  `ID_GERENTE` INT NOT NULL,
  `nombreGerente` VARCHAR(32) NOT NULL,
  `apellidoGerente` VARCHAR(32) NOT NULL,
  `rucGerente` INT NOT NULL,
  `dniGerente` INT NOT NULL,
  `emailGerente` VARCHAR(32) NOT NULL,
  `celularGerente` INT NOT NULL,
  PRIMARY KEY (`ID_GERENTE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`pago_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`pago_contrato` (
  `ID_PAGO_CONTRATO` INT NOT NULL,
  `fechaInicioContrato` INT NOT NULL,
  `fechaFinContrato` INT NOT NULL,
  `cantidadMesesContrato` INT NOT NULL,
  PRIMARY KEY (`ID_PAGO_CONTRATO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`contrato` (
  `ID_CONTRATO` INT NOT NULL,
  `FK_ID_GERENTE` INT NOT NULL,
  `FK_PAGO_CONTRATO` INT NOT NULL,
  `fechaPagoContrato` DATETIME NOT NULL,
  PRIMARY KEY (`ID_CONTRATO`),
  INDEX `idPagoContrato_idx` (`FK_PAGO_CONTRATO` ASC) VISIBLE,
  INDEX `idGerente_idx` (`FK_ID_GERENTE` ASC) VISIBLE,
  CONSTRAINT `idGerente`
    FOREIGN KEY (`FK_ID_GERENTE`)
    REFERENCES `proyecto_restaurante`.`gerente` (`ID_GERENTE`),
  CONSTRAINT `idPagoContrato`
    FOREIGN KEY (`FK_PAGO_CONTRATO`)
    REFERENCES `proyecto_restaurante`.`pago_contrato` (`ID_PAGO_CONTRATO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`proveedor` (
  `ID_PROVEEDOR` INT NOT NULL,
  `nombreProveedor` VARCHAR(45) NOT NULL,
  `rucProveedor` VARCHAR(45) NOT NULL,
  `FK_ID_CONTRATO` INT NOT NULL,
  PRIMARY KEY (`ID_PROVEEDOR`),
  INDEX `idContrato_idx` (`FK_ID_CONTRATO` ASC) VISIBLE,
  CONSTRAINT `idContratoProveedor`
    FOREIGN KEY (`FK_ID_CONTRATO`)
    REFERENCES `proyecto_restaurante`.`contrato` (`ID_CONTRATO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`bebida` (
  `ID_BEBIDA` INT NOT NULL,
  `nombreBebida` VARCHAR(45) NOT NULL,
  `detalleBebida` VARCHAR(100) NOT NULL,
  `precioBebida` DECIMAL(3,2) NOT NULL,
  `stockBebida` INT NOT NULL,
  `FK_ID_PROVEEDOR` INT NOT NULL,
  PRIMARY KEY (`ID_BEBIDA`),
  INDEX `FK_ID_PROVEEDOR_idx` (`FK_ID_PROVEEDOR` ASC) VISIBLE,
  CONSTRAINT `idProveedorBebida`
    FOREIGN KEY (`FK_ID_PROVEEDOR`)
    REFERENCES `proyecto_restaurante`.`proveedor` (`ID_PROVEEDOR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`cliente` (
  `ID_CLIENTE` INT NOT NULL,
  `nombreCliente` VARCHAR(45) NOT NULL,
  `apellidoCliente` VARCHAR(45) NOT NULL,
  `dniCliente` INT NOT NULL,
  `rucCliente` INT NOT NULL,
  `celularCliente` INT NULL DEFAULT NULL,
  `correoCliente` VARCHAR(45) NULL DEFAULT NULL,
  `direccionCliente` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CLIENTE`),
  UNIQUE INDEX `idCliente_UNIQUE` (`ID_CLIENTE` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`cocinero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`cocinero` (
  `ID_COCINERO` INT NOT NULL,
  `nombreCocinero` VARCHAR(45) NOT NULL,
  `apellidoCocinero` VARCHAR(45) NOT NULL,
  `dniCocinero` INT NOT NULL,
  `celularCocinero` INT NULL DEFAULT NULL,
  `FK_ID_CONTRATO` INT NOT NULL,
  PRIMARY KEY (`ID_COCINERO`),
  INDEX `idContrato_idx` (`FK_ID_CONTRATO` ASC) VISIBLE,
  CONSTRAINT `idContratoCocinero`
    FOREIGN KEY (`FK_ID_CONTRATO`)
    REFERENCES `proyecto_restaurante`.`contrato` (`ID_CONTRATO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`insumo` (
  `ID_INSUMO` INT NOT NULL,
  `nombre_insumo` VARCHAR(25) NOT NULL,
  `cantidad_insumo` INT NOT NULL,
  `precio_insumo` DOUBLE NOT NULL,
  `FK_ID_PROVEEDOR` INT NOT NULL,
  PRIMARY KEY (`ID_INSUMO`),
  INDEX `idProveedor_idx` (`FK_ID_PROVEEDOR` ASC) VISIBLE,
  CONSTRAINT `idProveedorInsumo`
    FOREIGN KEY (`FK_ID_PROVEEDOR`)
    REFERENCES `proyecto_restaurante`.`proveedor` (`ID_PROVEEDOR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`cocina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`cocina` (
  `ID_COCINA` INT NOT NULL,
  `FK_ID_COCINERO` INT NOT NULL,
  `FK_ID_INSUMO` INT NOT NULL,
  `tiempoCocina` INT NOT NULL,
  `recetaComida` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`ID_COCINA`),
  INDEX `idCocinero_idx` (`FK_ID_COCINERO` ASC) VISIBLE,
  INDEX `idInsumo_idx` (`FK_ID_INSUMO` ASC) VISIBLE,
  CONSTRAINT `idCocinero`
    FOREIGN KEY (`FK_ID_COCINERO`)
    REFERENCES `proyecto_restaurante`.`cocinero` (`ID_COCINERO`),
  CONSTRAINT `idInsumo`
    FOREIGN KEY (`FK_ID_INSUMO`)
    REFERENCES `proyecto_restaurante`.`insumo` (`ID_INSUMO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`comida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`comida` (
  `ID_COMIDA` INT NOT NULL,
  `nombreComida` VARCHAR(45) NOT NULL,
  `detalleComida` VARCHAR(100) NOT NULL,
  `precioComida` DECIMAL(3,2) NOT NULL,
  `StockComida` INT NOT NULL,
  `FK_ID_COCINA` INT NOT NULL,
  PRIMARY KEY (`ID_COMIDA`),
  INDEX `idCocina_idx` (`FK_ID_COCINA` ASC) VISIBLE,
  CONSTRAINT `idCocina`
    FOREIGN KEY (`FK_ID_COCINA`)
    REFERENCES `proyecto_restaurante`.`cocina` (`ID_COCINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`comprobante_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`comprobante_pago` (
  `ID_COMPROBANTE_PAGO` INT NOT NULL,
  `tipoComprobantePago` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_COMPROBANTE_PAGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`mesero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`mesero` (
  `ID_MESERO` INT NOT NULL,
  `nombreMesero` VARCHAR(45) NOT NULL,
  `apellidoMesero` VARCHAR(45) NOT NULL,
  `dniMesero` INT NOT NULL,
  `celularMesero` INT NULL DEFAULT NULL,
  `FK_ID_CONTRATO` INT NOT NULL,
  PRIMARY KEY (`ID_MESERO`),
  UNIQUE INDEX `idMesero_UNIQUE` (`ID_MESERO` ASC) VISIBLE,
  INDEX `idContrato_idx` (`FK_ID_CONTRATO` ASC) VISIBLE,
  CONSTRAINT `idContratoMesero`
    FOREIGN KEY (`FK_ID_CONTRATO`)
    REFERENCES `proyecto_restaurante`.`contrato` (`ID_CONTRATO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`metodo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`metodo_pago` (
  `ID_METODO_PAGO` INT NOT NULL,
  `tipoMetodoPago` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_METODO_PAGO`),
  UNIQUE INDEX `idMetodoPago_UNIQUE` (`ID_METODO_PAGO` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`pedido` (
  `ID_PEDIDO` INT NOT NULL,
  `FK_ID_CLIENTE` INT NOT NULL,
  `FK_ID_MESERO` INT NOT NULL,
  `costoTotalPedido` DECIMAL(4,2) NOT NULL,
  `fechaPedido` DATETIME NOT NULL,
  `FK_ID_COMIDA` INT NOT NULL,
  `FK_ID_BEBIDA` INT NOT NULL,
  PRIMARY KEY (`ID_PEDIDO`),
  INDEX `idMesero_idx` (`FK_ID_MESERO` ASC) VISIBLE,
  INDEX `idCliente_idx` (`FK_ID_CLIENTE` ASC) VISIBLE,
  INDEX `idBebida_idx` (`FK_ID_BEBIDA` ASC) VISIBLE,
  INDEX `idComidaPedido_idx` (`FK_ID_COMIDA` ASC) VISIBLE,
  CONSTRAINT `idBebida`
    FOREIGN KEY (`FK_ID_BEBIDA`)
    REFERENCES `proyecto_restaurante`.`bebida` (`ID_BEBIDA`),
  CONSTRAINT `idCliente`
    FOREIGN KEY (`FK_ID_CLIENTE`)
    REFERENCES `proyecto_restaurante`.`cliente` (`ID_CLIENTE`),
  CONSTRAINT `idComida`
    FOREIGN KEY (`FK_ID_COMIDA`)
    REFERENCES `proyecto_restaurante`.`comida` (`ID_COMIDA`),
  CONSTRAINT `idMesero`
    FOREIGN KEY (`FK_ID_MESERO`)
    REFERENCES `proyecto_restaurante`.`mesero` (`ID_MESERO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_restaurante`.`reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_restaurante`.`reporte` (
  `ID_REPORTE` INT NOT NULL,
  `FK_ID_COMPROBANTE` INT NOT NULL,
  `FK_ID_METODO_PAGO` INT NOT NULL,
  `FK_ID_PEDIDO` INT NOT NULL,
  `detalleReporte` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_REPORTE`),
  UNIQUE INDEX `idReporte_UNIQUE` (`ID_REPORTE` ASC) VISIBLE,
  INDEX `idComprobante_idx` (`FK_ID_COMPROBANTE` ASC) VISIBLE,
  INDEX `idMetodoPago_idx` (`FK_ID_METODO_PAGO` ASC) VISIBLE,
  INDEX `idPedido_idx` (`FK_ID_PEDIDO` ASC) VISIBLE,
  CONSTRAINT `idComprobante`
    FOREIGN KEY (`FK_ID_COMPROBANTE`)
    REFERENCES `proyecto_restaurante`.`comprobante_pago` (`ID_COMPROBANTE_PAGO`),
  CONSTRAINT `idMetodoPago`
    FOREIGN KEY (`FK_ID_METODO_PAGO`)
    REFERENCES `proyecto_restaurante`.`metodo_pago` (`ID_METODO_PAGO`),
  CONSTRAINT `idPedido`
    FOREIGN KEY (`FK_ID_PEDIDO`)
    REFERENCES `proyecto_restaurante`.`pedido` (`ID_PEDIDO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
